name: 'Build and Test Hamarr'

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -S . -B ${{runner.workspace}}/build  -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_HAMARR_TESTS=ON -DBUILD_HAMARR_EXAMPLES=OFF -DINSTALL_LIBRARY=OFF

    - name: Build Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build build --config $BUILD_TYPE --target tests

    - name: Run Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ${{runner.workspace}}/build/test/tests
