name: 'Build and Test'

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {name: ubuntu-gcc-9, os: ubuntu-latest, cc: gcc-9, cxx: g++-9}
          - {name: ubuntu-clang-9, os: ubuntu-latest, cc: clang-9, cxx: clang++-9}
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -S . -B ${{runner.workspace}}/build  -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_HAMARR_TESTS=ON -DBUILD_HAMARR_EXAMPLES=OFF -DINSTALL_LIBRARY=OFF

    - name: Build Tests
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build --config $BUILD_TYPE --target tests

    - name: Run Tests
      working-directory: ${{runner.workspace}}
      shell: bash
      run: ${{runner.workspace}}/build/test/hamarr_tests
